// All columns in your table (keep this list in same order as DB)
// MASTER DOCTOR COLUMNS (common for both DBs)
const masterCampColumnsD2C = [
  "dr_code",
  "plandate",
  "plantime",
  "location",
  "state",
  "city",
  "plantype",
  "statuscode",
  "assignto",
  "remark",
  "approveby",
  "approvon",
  "createdby",
  "createdon",
  "modifyby",
  "modifyon",
  "isactive",
  "longitude",
  "latitude",
  "hq",
  "attendedby",
  "epochdate",
  "planwith",
  "exit_approveby",
  "exit_approvon",
  "strips_used",
];

const masterCampColumnsLloyd = [
  "dr_code",
  "plandate",
  "plantime",
  "location",
  "state",
  "city",
  "plantype",
  "statuscode",
  "assignto",
  "remark",
  "approveby",
  "approvon",
  "createdby",
  "createdon",
  "modifyby",
  "modifyon",
  "isactive",
  "longitude",
  "latitude",
  "hq",
  "attendedby",
  "epochdate",
  "planwith",
];

export { masterCampColumnsD2C, masterCampColumnsLloyd };
